### ISSUE TITLE
Not working with live script (.mlx)

### ISSUE THREAD

**Issue by asarkar1** [scottclowe/matlab-schemer#32]
Hello, 
First of all, thank you for the color schemes. As I run the dark mode, it seems to be ignoring the live scripts. The live scripts are still unchanged (regular white background). It would be helpful if you may address this.

**Comment by scottclowe** [comment]
I can only do what you can already manually do in the Preferences window.

You can't change the colour scheme for live scripts in the Preferences window, so I can't automate it as part of this package.
