### ISSUE TITLE
Scheme does not alter "Views" tab on Project Manager

### ISSUE THREAD

**Issue by tplobo** [scottclowe/matlab-schemer#35]
Running "schemer_import" alters every tab and window region of MATLAB, except "Views" in the Project Manager:

![Views Tab on Project Manager](https://user-images.githubusercontent.com/40567154/144442004-bc507362-9ad5-4ed6-8b97-1f766958794d.png)

**Comment by scottclowe** [comment]
Unfortunately, the colours of the Views tab can not be customized.
