### ISSUE TITLE
Bug(?) in "schemer_export" Line 179

### ISSUE THREAD

**Issue by LoGGoL** [scottclowe/matlab-schemer#9]
Line 179:
if ~isnumeric(fname)

I guess it should be 
if ~isnumeric(flag_mode)

Regards,

**Comment by scottclowe** [comment]
You are correct! Thanks for pointing this out.

After I created this bug, I only tested the code by exporting through the GUI before releasing it...

It's now fixed.

**Comment by scottclowe** [comment]
Also, thanks for creating a GitHub account just to open this issue. I appreciate it!
